version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - NODE_ENV=production
    depends_on:
      - client
  client:
    build: ./client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
